#!/bin/bash
#
# BASH AWS - list resources from the cli without much effort
# https://github.com/herself/baws

read -d '' REGIONS << EOF
us-east-1       N. Virginia
us-west-2       Oregon
us-west-1       N. California
eu-west-1       Ireland
eu-central-1    Frankfurt
ap-southeast-1  Singapore
ap-southeast-2  Sydney
ap-northeast-1  Tokyo
sa-east-1       Sao Paulo
EOF

read -d '' ACTIONS << EOF
vpc             List VPCs in a chosen region
instances       List instances in a chosen region and VPC
cinstances      Continously list instances in a chosen region and VPC
EOF

list_instances() {
  REGION=$1
  VPC=$2

  echo "$REGION" >> tmp
  echo "$VPC" >> tmp

  aws ec2 describe-instances --region "${REGION}" --filters Name=vpc-id,Values="${VPC}" \
    --query 'Reservations[*].Instances[*].[Placement.AvailabilityZone, State.Name, InstanceId, PrivateIpAddress, InstanceType, Tags[?Key==`Name`].Value]' | jq -r 'flatten(1) | map(flatten) | map(map(select(type == "string") |if test(" ") then sub(" "; "-") else . end)) | map(join(" ")) | join("\n")'
}
export -f list_instances

list_vpcs() {
  REGION=$1

  aws ec2 describe-vpcs --region "$REGION" --query 'Vpcs[*].[VpcId, Tags[?Key==`Name`].Value]' | jq -r 'map(flatten) | map(join(" ")) | join ("\n")'
}
export -f list_vpcs

list_regions() {
  echo -e "$REGIONS"
}
export -f list_regions

command -v fzf >/dev/null 2>&1 || { echo >&2 "I require fzf but it's not installed."; exit 1; }
command -v aws >/dev/null 2>&1 || { echo >&2 "I require aws but it's not installed."; exit 1; }
command -v jq >/dev/null 2>&1 || { echo >&2 "I require jq but it's not installed."; exit 1; }
jq 2>&1 | grep 1.5 >/dev/null|| { echo >&2 "I require jq version 1.5"; exit 1; }

if [[ -z $1 ]]; then
  ACTION=$(echo -e "$ACTIONS" | fzf | awk '{ print $1 }')
else
  ACTION=$1
fi

if [[ -z $2 ]]; then
  REGION=$(list_regions | fzf | awk '{ print $1 }')
else
  REGION=$2
fi

case $ACTION in
vpc)
  list_vpcs "$REGION"
  ;;
instances)
  VPC=$(list_vpcs "$REGION" | fzf | awk '{ print $1 }')
  list_instances "$REGION" "$VPC" | column -t
  ;;
cinstances)
  VPC=$(list_vpcs "$REGION" | fzf | awk '{ print $1 }')
  watch -d -n 5 "bash -c 'list_instances $REGION $VPC' | column -t"
  ;;
*)
  echo "Wrong arguments! They must be one of"
  echo "$ACTIONS"
  echo "Or simply run the script without them to get an fzf dialog"
  exit 1
  ;;
esac
